sudo: false
language: python
python:
  - '2.7'
  - '3.4'
  - '3.5'
  - '3.6'
env:
  global:
    - DB=postgres
  matrix:
    - DJANGO=">=1.11,<2.0"
install:
  - pip install -q psycopg2 coverage flake8 Django$DJANGO django-nose>=1.4
before_script:
  - psql -c 'CREATE DATABASE entity_emailer;' -U postgres
script:
  - flake8 .
  - coverage run setup.py test
  - coverage report --fail-under=100
