# Generated by Django 3.2.19 on 2023-06-01 13:10

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    replaces = [('entity_emailer', '0001_initial'),
                ('entity_emailer', '0002_auto_20170919_1653'),
                ('entity_emailer', '0003_email_exception'),
                ('entity_emailer', '0004_email_num_tries')]

    dependencies = [
        ('entity_event', '0001_initial'),
        ('entity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_uid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('subject', models.CharField(max_length=256)),
                ('from_address', models.CharField(default='', max_length=256)),
                ('uid', models.CharField(default=None, max_length=100, null=True, unique=True)),
                ('scheduled', models.DateTimeField(default=datetime.datetime.utcnow, null=True)),
                ('sent', models.DateTimeField(default=None, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entity_event.event')),
                ('recipients', models.ManyToManyField(to='entity.Entity')),
                ('exception', models.TextField(default=None, null=True)),
                ('num_tries', models.IntegerField(default=0)),
            ],
        ),
    ]
